/// Task domain model — pure Dart, no Flutter imports.
library;

import 'package:meta/meta.dart';

/// A monthly financial task that the user should complete.
///
/// Tasks are the action layer — they translate the allocation plan into
/// concrete steps ("Transfer X TWD to wallet Y this month").
@immutable
class Task {
  /// Creates an immutable [Task].
  const Task({
    required this.id,
    required this.month,
    required this.title,
    required this.amount,
    required this.kind,
    required this.auto,
    required this.isDone,
    required this.sourceRef,
    this.destinationAccountRef,
  });

  /// Unique identifier.
  final String id;

  /// Month this task belongs to, in `'YYYY-MM'` format.
  final String month;

  /// User-visible task description.
  final String title;

  /// Task target amount in integer cents (分).
  final int amount;

  /// Task kind string (e.g. `'transfer'`, `'topup'`).
  final String kind;

  /// Whether this task was auto-generated by the allocation engine.
  final bool auto;

  /// Whether the user has marked this task as done.
  final bool isDone;

  /// Reference to the source entity (wallet id, income id, etc.).
  final String sourceRef;

  /// Optional: the account to transfer money into.
  final String? destinationAccountRef;

  // ── Immutable helpers ────────────────────────────────────────────────────

  /// Returns a copy of this task with the given fields replaced.
  Task copyWith({
    String? id,
    String? month,
    String? title,
    int? amount,
    String? kind,
    bool? auto,
    bool? isDone,
    String? sourceRef,
    Object? destinationAccountRef = _sentinel,
  }) {
    return Task(
      id: id ?? this.id,
      month: month ?? this.month,
      title: title ?? this.title,
      amount: amount ?? this.amount,
      kind: kind ?? this.kind,
      auto: auto ?? this.auto,
      isDone: isDone ?? this.isDone,
      sourceRef: sourceRef ?? this.sourceRef,
      destinationAccountRef: destinationAccountRef == _sentinel
          ? this.destinationAccountRef
          : destinationAccountRef as String?,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Task &&
        other.id == id &&
        other.month == month &&
        other.title == title &&
        other.amount == amount &&
        other.kind == kind &&
        other.auto == auto &&
        other.isDone == isDone &&
        other.sourceRef == sourceRef &&
        other.destinationAccountRef == destinationAccountRef;
  }

  @override
  int get hashCode => Object.hash(
        id,
        month,
        title,
        amount,
        kind,
        auto,
        isDone,
        sourceRef,
        destinationAccountRef,
      );
}

// Sentinel value for nullable copyWith parameters.
const Object _sentinel = Object();
